adding book CRUD
AlterTrap/book-management-be pull request #2
Opened 2023-09-05 06:08 UTC by KhaiNd3

2023-09-05 13:15 UTC, SillyBoomer commented on .env
> +DEV_DB_NAME=book-manager
@KhaiNd3 
Thiếu 1 dòng mới cuối file

2023-09-05 13:16 UTC, SillyBoomer commented on index.js
> +app.use("/api/book", bookRouter);
@KhaiNd3 
Tên thực thể theo số nhiều, đổi book -> books

2023-09-05 13:19 UTC, SillyBoomer commented on src/controllers/exampleController.js
> +const { Example } = require("../models/example");
@KhaiNd3 
Example không có gì thay đổi về mặt logic, không push lên.

2023-09-05 13:38 UTC, SillyBoomer commented on src/migrations/20230904092651-create-book-table.js
> +  return db.createTable("book", {
@KhaiNd3 
Sửa tên bảng thành số nhiều.

2023-09-05 13:38 UTC, SillyBoomer commented on src/models/book.js
> +      // defaultValue: DataTypes.literal("CURRENT_TIMESTAMP"),
@KhaiNd3 
Comment không có ý nghĩa giải thích thì xóa đi.

2023-09-05 13:38 UTC, SillyBoomer commented on src/utils/seeders/example.js
> +<<<<<<< HEAD
@KhaiNd3 
Vẫn còn conflict.

2023-09-05 15:13 UTC, KhaiNd3 commented
![create_case1](https://github.com/AlterTrap/book-management-be/assets/51858845/4fb23d61-311c-407c-a487-140f28172ed5)
![create_case2](https://github.com/AlterTrap/book-management-be/assets/51858845/a977d507-5dd4-4e1c-8b33-f6999c08fc4b)
![create_case3](https://github.com/AlterTrap/book-management-be/assets/51858845/e4b4de6a-2a2f-4edf-97f0-b60a2da25114)
![create_case4](https://github.com/AlterTrap/book-management-be/assets/51858845/8e982182-0fbc-470e-8bea-1d4620e0f588)
![create_case5](https://github.com/AlterTrap/book-management-be/assets/51858845/ebc5489f-0141-4125-ae0e-838adef1bc76)
![create_case6](https://github.com/AlterTrap/book-management-be/assets/51858845/22af9fa8-2b4a-4675-9536-b4e07a75a6dd)
![deletecase](https://github.com/AlterTrap/book-management-be/assets/51858845/51c7b549-c196-49c2-a802-7abc267e2e3b)
![read_case1](https://github.com/AlterTrap/book-management-be/assets/51858845/f5d96252-c85b-4399-9ed2-8492e793b9c5)
![update_case1](https://github.com/AlterTrap/book-management-be/assets/51858845/4a8e07e9-87ed-4eda-8bb3-43fcf65bd621)
![update_case2](https://github.com/AlterTrap/book-management-be/assets/51858845/fe08f29f-4dc0-442f-a988-1be0b674a9d5)
![update_case3](https://github.com/AlterTrap/book-management-be/assets/51858845/a327a0d3-7a96-429c-92a3-4080e5fa30da)
![update_case4](https://github.com/AlterTrap/book-management-be/assets/51858845/a32ecbbe-72a2-40f1-8317-4a7ac9fe5d3b)
![update_case5](https://github.com/AlterTrap/book-management-be/assets/51858845/d8f8ba27-29bc-483a-88be-a4ae7c834808)
![update_case6](https://github.com/AlterTrap/book-management-be/assets/51858845/d6599fa9-aae5-4e9b-80ea-f5a42070a233)

2023-09-05 15:26 UTC, KhaiNd3 commented
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/81fac5ec-ec4b-41aa-a01b-36fa134bda84)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/052b57cf-317d-46c8-b5a7-36f33e9e727e)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/1d1ef255-4f96-49c5-a33f-3964216abe41)

2023-09-06 05:54 UTC, KhaiNd3 commented
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/65ecb5d4-c59b-4ef4-aa4c-f0d39c535106)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/27326048-2205-4e47-bd85-e9796e2f7510)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e39980a2-80b2-4078-b9f4-2e2c76d6f649)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/745caef1-041f-4f49-956b-b6c001c9ea8f)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/5ee9e833-079b-404e-9a06-bb17573d8da9)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/f60a89b5-30e6-44f9-a9ab-2238ccb37311)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/6f78d39e-7aaa-43ea-87be-6f55198ddf22)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/194d813b-c64f-4efc-b62f-2501188e6d4d)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/768aa08f-f1f4-4174-ab5d-2ea03369a7bb)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/d738e2cb-a0de-4335-beef-e8b2cf5d4cdb)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/f5d02e37-b6af-4d12-b136-b6693a974eee)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/847f552c-d05c-4d6a-b7bb-ab90a28b5615)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/cdbfae6f-5858-49bc-944b-8540fa4a377e
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/d8c550f3-d6f6-48a7-b1b3-504308f89353)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9f5f8680-461e-434e-9a14-827ae13407a2)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b4631332-4318-444d-9524-139ebb02527a)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/4569a172-6fc3-455d-a6f5-e11d093171c0)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/3b5ed083-67a1-4c56-bb5b-6400b7a88cc2)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/60ce93e2-578e-4169-af42-8399550a71e8)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b39fbd48-641b-4389-8eaa-d6850d355ab8)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/55ec9883-c7ca-471f-b6fc-b9ffde40de16)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/892cc9ee-8e70-48e4-8c44-cb098bde72c2)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/3d98b817-5bdf-4c3d-9ec8-45e0f8df975d)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/97cf1835-7136-4e2f-9aef-00368a6dd403)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/894dee14-6879-4f20-83c3-e6ddeb9bcb3b)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/3c3977ef-2f62-4f30-8aef-8d69473ac628)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8d7e6552-2ba1-44b5-845d-1665b60ddef4)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/7093c681-b9a1-4669-8440-2803b71f864c)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/20bb92c6-86ac-4da4-b6da-74b41eb7a3d6)
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9095e729-2f0a-471d-95ed-67f388e0c6ac)

2023-09-06 13:38 UTC, SillyBoomer commented
@KhaiNd3 
Update book khi không có category bị lỗi
![image](https://github.com/AlterTrap/book-management-be/assets/88369228/64f7b96e-f07a-4a9d-9c4f-c55d15552139)

```
C:\Users\OS\Documents\project\book-management-be\src\controllers\bookController.js:58
  if (category.trim() === '') return res.status(422).json('Plz Input Category');
               ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at Object.update (C:\Users\OS\Documents\project\book-management-be\src\controllers\bookController.js:58:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

2023-09-07 05:59 UTC, KhaiNd3 commented
| First Header  | Second Header |
| ------------- | ------------- |
| Find feature  |![image](https://github.com/AlterTrap/book-management-be/assets/51858845/917cfa4c-5799-40ac-a7f0-5d4d925a149d) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/7cbff49c-ba58-4e3f-9b82-e53c73486685) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/22ece98f-e9ea-4bcb-8c4f-bb4b0fc58bbb) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/1505f073-bfcb-4def-a44f-d25079e6778e) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/c47441d2-57cf-4e3d-8890-0758d2e73fe1) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9e91a5a1-d564-4330-bbdf-07f7fd489bb8) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/3704decf-6f53-4753-8a82-024746fe0f63) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/c9cc9d22-fb03-4ff0-afa1-6c23fb5738cf) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e665f12e-b5f4-4ed3-800c-bd2680fd4506) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/bc32c9d5-e56a-4402-9acc-d7301d404669) |
| Create feature | ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b6c60a84-d9c3-456d-ba7f-8e7cf2f670ee) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b5d8125d-ba4f-4489-bf9b-757147990ce6) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/18b76923-5efe-429c-a5f5-54c23d388e8c) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ebdb5a19-b8fc-485b-ba68-bb257585922e) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e5ccdd54-827e-4ce1-928c-0aca1f4b575f) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ca85482b-8bb2-4901-adc3-b3f8f55182a8) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/1b440b62-a99f-461d-818b-00c9c07f158a) |
| Update feature  | ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/247d8593-c693-4779-9d3d-48a19fd0a1c7) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/00085855-c8b1-47b7-b167-dc17d2e93279) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/39502593-4099-40ab-8ebc-d6422f937414) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/4ce14273-ca73-43d8-91aa-ee0b31f089e0) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/60115261-4892-42bf-960c-a7c32b57b59c) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/fa98402f-2f72-429f-ad9e-6b4e72a28611) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/7bf04271-187c-4769-8ea1-1d4db8c6e216) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/09a30dbe-5eb4-40a1-b442-64077eeeb2df) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/0de99a2c-3cd0-49be-a9ff-3863e70388c8) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/0c5d9acf-2e6d-427d-862c-97727e5b10ed) |
| Delete feature  | ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ad591fed-a695-4551-8800-8bc6c4425376) ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/5e90f349-c1ce-47f9-b4a6-fc74807aa209) |

2023-09-07 10:58 UTC, laihuynhnhatminh commented on src/controllers/bookController.js
>    if (existBook) return res.json('already exist');
Should be `${name} already exist`, so that FE could understand what they should change.

2023-09-07 11:00 UTC, laihuynhnhatminh commented on src/controllers/bookController.js
> +    return res.json('Book already exist check and use other name');
Or, use this error message to send for the create endpoint if book already exist too.

2023-09-07 11:01 UTC, laihuynhnhatminh commented on src/controllers/exampleController.js
> +  console.log(name);
Remove logger

2023-09-07 11:02 UTC, laihuynhnhatminh commented on src/controllers/exampleController.js
>    if (!name || name.trim() === '')
!name || !name.trim()

2023-09-07 11:02 UTC, laihuynhnhatminh commented on src/controllers/exampleController.js
>    if (!name || name.trim() === '')
!name || !name.trim()

2023-09-07 11:06 UTC, laihuynhnhatminh commented on src/utils/validation/bookValidation.js
> +const nameNotEmpty = (val) => {
validation function (return boolean) should start with "is", isNameEmpty, isNameNotEmpty, isExist, isNotExist, isCategoryNotEmpty, isValidID, etc...
Should checkout naming convention for different types of function.
for example: a function that return all books should be getAllBooks() - this is just an example.

2023-09-07 11:06 UTC, laihuynhnhatminh commented on src/utils/validation/bookValidation.js
> +const nameNotEmpty = (val) => {
https://viblo.asia/p/javascript-naming-conventions-1Je5Ea1A5nL

2023-09-07 11:36 UTC, laihuynhnhatminh requested changes
Please fix the comments

2023-09-08 03:29 UTC, KhaiNd3 commented on src/controllers/exampleController.js
> +  console.log(name);
that's examples.

2023-09-08 03:57 UTC, laihuynhnhatminh commented on src/controllers/exampleController.js
> +  console.log(name);
Okay, please fix the comment that does not belong to example then

2023-09-08 04:00 UTC, laihuynhnhatminh commented on src/controllers/bookController.js
>    if (existBook) return res.json('already exist');
Also, please research about HTTP Status Code, in this case should be
`res.status(409).json('Book already exist check and use other name')`

2023-09-08 04:01 UTC, laihuynhnhatminh commented on src/controllers/bookController.js
>    if (existBook) return res.json('already exist');
For certain case like invalid name/category should be 400 status code.

2023-09-08 04:49 UTC, KhaiNd3 commented
| First Header  | Second Header |
| ------------- | ------------- |
| Find feature  | no input query params ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/acbd9e52-469b-4e09-9e98-dd095cdfab2a) input name = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ce5dc0d9-a2fa-4c36-9ce7-93359180268d) input name = ' '  ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/889b2248-e622-4e3f-8988-26222615a655) input name = 'abc' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/d715f7f9-f1af-4bbe-a577-f8faa552ebdd) input name = 'xyz' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/c9614bcc-c220-4bbf-a770-d9d669451c93) input category = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/00cbbb7e-c76a-4d17-accb-3d21635ae34e) input category = ' '  ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8132c9ff-5811-4722-acb9-dbf6122c0a6b) input category = 'something else' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/664c76a2-185c-4d0a-beab-c9746f1d5591) input category = 'novel' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8eac2683-5430-40fb-9269-aadfa970197e) input createdAt = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/a96c3fcb-77c4-407b-b2a4-b9e1dada2e2e) input createdAt = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b5527d28-30af-4a82-a8ad-b6d9366cb847) input = '2019-09-30' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/d130cfc1-bc64-4d43-b3b0-abbafa5e850f) input='2023-09-06 ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/f0961420-7aef-4050-85e9-b7d7619bcbc4) input name&category&createdAt = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/2ca0eba6-57a0-4b78-b594-7a43c33d20a2) input name&category&createdAt = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/a76ec219-ed67-4050-b456-a34126301375) input name = 'sherlock' and category&createdAt = ' '  ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/4919b397-019d-464f-9ce4-8b401c387541) input category = 'text book' and name&createdAt = ' '  ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/442d7368-8559-4c2b-bf61-6e3b02de2fef) input createdAt = '2023-09-07' and name&category = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/7b273f32-5171-479e-a94e-f1e2d96b3a20) input name = 'vida' and category = 'no' and createdAt = '2023-09-07' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/de17d887-296f-41e5-a1fa-e236a9249145) input = 'g' and category = 'no' and createdAt = '2023-09-08 ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9aa58255-7a84-47de-aa5a-3efeef83b82f) input name = 'g' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e34dd0f6-1417-40d1-8f31-c4a40264b41c) input category = 't' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/bce24664-43b2-4d35-bf38-9be258368d11) input name='vida' and category = 'novel and createdAt = '2023-09-30' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ca098d81-52f1-4235-8173-4bf1abda1cf6) |
| Create feature  | no body input ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/6fb2479c-ef24-4a74-8fd1-4e3c2ca89d4c) input name = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/91bdb560-6d99-4bc7-96f3-b0a2bacae7a5) input name = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/55aa7abf-2118-4d41-8fd6-cf626ee216e8) input name = 'weeee' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/680f9044-735b-4737-8126-2e9a143e7f9d) input name = 'weeee' and category = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/762c8c2c-76a9-4d88-bc16-652527e30863) input name = 'weeee' and category = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b55a8fe8-1139-4d48-b43f-d43bc0be9425) input name = 'weeee' and category = 'something else' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9adcfb2b-6b13-450b-a211-89c024a0ee63) |
| Update feature  | input id param= 'abc' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/2254a0e7-64b4-4c04-adb5-c95ea7506c57) input param id ='37' with no input body ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/708b30c0-949b-4f23-b077-3913530fd5e8) input param id='37' with name = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/70c85353-b55b-43ba-99df-7ec71a44d3dd) input param id='37' with name = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ae789e8b-d209-4c8c-8a65-931271ec3bb9) input param id ='37' with name='abc' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8aef4647-7806-4a14-8ff4-1013037281fe) input param id='37' with name = 'abc' and category = '' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/eecb3208-43ee-477d-a30b-ec676cdad5b2) input param='37' with name = 'abc' and category = ' ' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/bd1fd3cf-f512-466f-9311-74ed016d4914) input param id='37' with name='abc' and category = 'novel' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/c7e6a7b6-087a-40c5-89fa-dddf049d630c) input param id='37' with name='xyz' and category='novel' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/dde44b86-119f-4ade-a39d-40b4cabba400) input param id='37' with name='wvy' and createdAt='2023-09-20' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8063895d-def3-46c1-85fb-a31f452ecc8f) |
| Delete feature  | input param id='abc234' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/7dea7b5d-1eb7-4cdf-8304-31abc67820da) input param id='38' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/cea75224-664c-4b58-bf5e-0b82d085df9f) input param id='37' ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/dc154498-474c-4725-b970-2d939b66d371) |

2023-09-08 13:31 UTC, laihuynhnhatminh approved these changes
LGTM

2023-09-08 13:34 UTC, merged