add login and register function
AlterTrap/book-management-be pull request #7
Opened 2023-10-04 15:57 UTC by KhaiNd3

2023-10-04 16:27 UTC, KhaiNd3 commented
| First Header  | Second Header |
| ------------- | ------------- |
| Register function  | no input : ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/24753120-3948-4af8-981c-4aacc41e0e1f) username = abc: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/5d545f21-ebed-4a9f-afab-9f3812ee1544) username = abcdef: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/09596b80-b0fb-4230-87ed-2f8deb9063e0) username = abcdef & password = 123: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/f1e3a3d7-f840-4ac8-8fa2-4bd2df23358b) username = abcdef & password = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e46245cf-3100-4d9e-8907-5016918b64c2) username = abcdef & password = 123456 & passwordCfm = 123: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/fda9067d-ebaf-4d9b-a171-ebf4ec03a86d) username = abcdef & password = 123456 & passwordCfm = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8ec1852d-4dfa-4097-880f-731222883282) username = abcdef & password = A123456 & passwordCfm = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/402040a9-ee30-4940-a7f6-b78f2b0c5403) username = abcdef & password = A123456 & passwordCfm = A123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/5e3a89ee-9b08-4cb7-a45a-8d9fd93a6d1f) username = abcdef & password = A123456 & passwordCfm = A123456 (second time): ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8e40bcb8-d93d-44bc-adba-7c4026ecad61)|
| Login function | no input: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/b1df9083-5e0a-46d4-a552-4aaee010a380) username = abc: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/bfe5e196-b716-4e4b-8647-bc193ec4dd88) username = abcdef: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e6ae7a1e-ebd2-466b-adad-71df131b9519) username = abcdef & password = 123: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/061bd77a-629f-47a9-9531-2d4105a800f1) username = abcdef & password = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/75cfd3d1-1dbe-48a7-8a59-28fc892c5804) username = abcdef & password = B123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/2f230e10-0cb8-4fdc-aadd-cf0f76f34bfc) username = abcdef & password = A123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/dba1fc24-6308-40a5-b483-f5a145432381) |

2023-10-05 07:56 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +    return res.status(400).json('Username Not enough 6 letters');
Define lại username thì nên được ở định dạng thế nào? vì đơn thuần không trim username thì "a          " cũng là đủ length.
Trường hợp người ta đặt username kiểu "A me may ngu" hay "Oh!@#!@#!%&^"  cũng được à?

2023-10-05 07:58 UTC, laihuynhnhatminh commented on src/utils/validation/validation.js
> +const isEnoughLength = (val) => {
Trường hợp khách hàng muốn đổi lại username length hơn 10, password hơn 6, thì không lẽ viết 2 validation function?

2023-10-05 08:01 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +  const checkUps = isOneUpscalePass(password);
Tương tự username, define lại password chứ không kiểu password ni cho 1 tỉ whitespace vô cũng ok luôn?

2023-10-05 08:06 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +  const checkUps = isOneUpscalePass(password);
Trước khi làm thì nên làm ra 1 cái note ghi ra, điều kiện cho username và password cho cái note đó rồi chúng ta sẽ thiết kế validation dựa trên những gì mà mình note hoặc define trước. Trong code, việc quan trọng nhất là planning cho những phần mình làm. Vì hắn sẽ giúp mình bỏ đi những cái mình có thể bỏ sót hoặc, deploy xong và quên mất a,b,c gì đó. 
Bước này gọi là specification.

2023-10-05 08:07 UTC, laihuynhnhatminh commented on src/utils/validation/validation.js
> +const isEnoughLength = (val) => {
Cơ bản của validation là 1 function dùng lại được nhiều lần và phải có tính generic cao, không nên ép nó phải static, không dùng lại được thì mất ý nghĩa cho 1 function utils

2023-10-05 08:28 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +  const CheckPassword = isEnoughLength(password);
Naming, camel-case cho Javascript thôi. Không nên viết kiểu này

2023-10-05 08:32 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
Về mặt bằng cung thì sau khi login/register nên trả lại data về user và phương thức authentication, ví dụ jwt token ( phần ni Ạkira sẽ giải thích cho anh sau.)
Đây là hình ảnh ví dụ cho 1 response từ login
![image](https://github.com/AlterTrap/book-management-be/assets/13594064/aec2ee16-e3b2-475b-8370-108e9df5b71b)

2023-10-05 08:33 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
Tất nhiên app của anh không cần phức tạp rứa, nhưng nên trả về data trong register/login để FE dùng, ví dụ nếu anh có 1 màn hình chỉ có câu hello user "ABCXYZ" thì chúng ta sẽ lấy data từ đâu?

2023-10-05 08:37 UTC, laihuynhnhatminh requested changes
- Cần redefined username, password có định dạng như thế nào.
- Cần sửa lại validation functions xem lại cách code function.
- Cần sửa lại data trả về sau khi login/register (authentication ra sao? @HamanoAkira sẽ giải thích và hướng dẫn).

2023-10-05 12:28 UTC, SillyBoomer commented
@KhaiNd3 
Tới thời điểm nên sử dụng thư viện validation.
Định nghĩa lại các hàm validate sẽ rất mất công.
Có thể chọn một trong số các thư viện hay dùng như express-validator, joi, zod...

Có thể bắt đầu với express-validator cho dễ:
https://express-validator.github.io/docs/

2023-10-06 01:52 UTC, KhaiNd3 commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
cách anh đang sử dụng là authentication là lưu trong cookie, thì trong cookie chỉ lưu mỗi thông tin session id thôi không có lưu thông tin người dùng, nếu muốn lấy thông tin người dùng cho FE thì sẽ có 2 cách 1 là trả về bên response 2 là dùng 1 thư viện riêng để lưu vô cookie, ví dụ như : cookie-parse.

2023-10-06 06:13 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
Về mặt bảo mật lẫn so với cách nhiều công ty đang làm thì thường sẽ không login rồi lưu thông vào session id như ri, sẽ rất không an toàn như sử dụng JWT (bearer token) vì nếu anh muốn tách request về API thì cần phải có authentication thì mới được dùng API như tạo, update, xóa sách.
- Cái vấn đề login/register ở đây tạo ra token là để bảo mật cho FE lẫn BE. Đặc biệt là BE.
- Còn việc trả user data trong login/register thì nên trả về để cho FE lưu user data bằng store (nguyên lý quản lý global data của FE, đối với React thì là Redux) chớ thường ít lưu trong data cookie.

2023-10-06 06:15 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
https://viblo.asia/p/jwt-tu-co-ban-den-chi-tiet-LzD5dXwe5jY
Đọc và tìm hiểu về JWT, phương thức bảo mật được dùng nhiều nhất cho thời điểm hiện tại cho các website, bảo mật cho FE và BE, không cho người dùng ngoài sử dụng api để ảnh hưởng tới DB BE.

2023-10-06 06:18 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
- Việc học JWT là khởi đầu cho việc sau này nếu anh làm BE sẽ mở rộng ra refresh token, OTP hay còn nhiều cách bảo mật khác cho hệ thống lớn.
- Việc sử dùng cookie session thì cũng không sai, nhưng nếu có thể mình thử nghiên cứu và áp dụng jwt thử. Vì việc anh dùng JWT token sẽ dẫn tới anh nghiên cứu vào sử dùng 1 cái authentication cho app global hoặc chỉ dùng trên 1 nhánh nào đó của API.
- Ví dụ GUEST chỉ có thể xem sách, còn USER/AUTHOR tạo và sở hữu sách với có thể edit/delete/create.

2023-10-06 06:20 UTC, laihuynhnhatminh commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
Mình nên hiểu cả session lẫn JWT, nó rất quan trọng cho việc phát triển API, giờ mình đang đi hướng RESTful API thì mình nên xem thử cách ổn định nhất là gì? Còn sau ni nếu anh làm ở công ty và làm microservice quản lý 1 account liên quan tới nhiều app chung của 1 hệ thống, session sẽ có thể được áp dụng.

2023-10-06 15:49 UTC, KhaiNd3 commented
| First Header  | Second Header |
| ------------- | ------------- |
| Register function  | no input: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/c06297e8-9abd-4a59-af61-acdaac7c01ef) username = abc: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e2af4164-3c5b-43bf-a567-5b074028b810) username = abcxyz: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/85077e76-d5ea-4f56-b04f-6dd9c15085a4) username = abcxyz & password = 123: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/971b6076-5e09-41c8-bd7c-fe0937a34588) username = abcxyz & password = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9f42fac8-a8f2-49b9-a61b-30ca002fd239) username = abcxyz & password = B123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/837714ce-3442-4b0f-94ae-a04d6796d632) username = abcxyz & password = B123456 & passwordCfm = 123: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/a2c44d04-99ca-463c-a0a6-39b7605d4da6) username = abcxyz & password = B123456 & passwordCfm = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ca0d7f90-2617-4b17-8baf-154db88fd063) username = abcxyz & password = B123456 & passwordCfm = A123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/bba7b881-f726-44b0-9eaa-e38ac0a8190c) username= abcxyz & password = B123456 & passwordCfm = B123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/a316a43b-2e3b-4dce-87c2-b746174de37e) username = "      ": ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/e3ef9969-4e70-4488-969f-1f74e66c0cf5) username = !#$@%$: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8cfbf47a-34b0-4af5-a93b-7ace53973749) username = "nguyen dong khai": ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/210bdbb5-ade9-431c-856e-f5f0af698184) username = "      " & password = "      " & passwordCfm = "      ": ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/05029750-8cd9-4d91-abe3-5784549db9cb) |
| Login function  | no input: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/9ea300d9-3137-429d-8620-f19ff3202654) username = abc: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/90d10887-137b-4aaf-8dfe-54aaf1518b9a) username= abcxyz: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/95e6d6b7-850e-4974-a85b-ee424bfdb5ea) username= abcxyz & password = 123: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/42b26efa-0365-4e5f-8e46-d07657d1dec9) username= abcxyz & pasword = 123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/60f37be5-2c56-48fa-8e6a-eba308e61976) username = abcxyz & password = B123456: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/ff15359b-3f17-450c-a8c0-c78e8c7310c0) username = !@#$%^: ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/fc5b4c5f-3ecd-4372-82b3-29b8360a6a77) username = "      ": ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/f5b7ad40-c711-46f4-b617-38be982701df) username = "nguyen dong khai": ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/8efd2324-afb3-4654-a25f-11b5515f313a) username = "      " & password = "      ": ![image](https://github.com/AlterTrap/book-management-be/assets/51858845/69f602e3-cafd-4091-8c22-508f6bed407c) |

2023-10-07 04:28 UTC, KhaiNd3 commented on src/utils/validation/validation.js
> +const isEnoughLength = (val) => {
đã fix

2023-10-07 04:28 UTC, KhaiNd3 commented on src/controllers/authController.js
> +  const checkUps = isOneUpscalePass(password);
đã fix

2023-10-07 04:34 UTC, SillyBoomer commented on index.js
> +    secret: 'mysupersecrect',
@KhaiNd3 
Secret là thông tin quan trọng, không nên để ở đây.
Để ở đây thì bất cứ ai có khả năng clone về được đều thấy được.
Lưu nó vào trong .env, rồi lấy ra.
Đồng thời setup cho git loại bỏ .env ra, không biết thì gg hoặc chatgpt.
Loại .env ra khỏi git thì commit sẽ không theme .env vào dù mình có thay đổi nó.

2023-10-07 04:34 UTC, SillyBoomer commented on src/controllers/authController.js
> +    const getUser = await User.findOne({ where: { username } });
@KhaiNd3 
```await User.create({``` có trả về user, xem thử có dùng được không, nếu được thì không cần phải gọi .findONe một lần nưuã.

2023-10-07 04:34 UTC, SillyBoomer commented on src/controllers/authController.js
> +    return res.status(201).json(getUser);
@KhaiNd3 
Liệu chỗ này có trả luôn password về cho client không? Kiểm tra nếu có thì loại bỏ password ra.

2023-10-07 04:34 UTC, SillyBoomer commented on src/utils/passportconfig.js
> +  );
@KhaiNd3 
Lệnh debug này có cần thiết không?

2023-10-07 04:36 UTC, SillyBoomer commented on src/utils/validation/validation.js
> +      .regex(/^[a-zA-Z0-9_-]+$/, { message: 'Username is Valid' }),
@KhaiNd3 
Sai thông báo lỗi, chỗ này phải là invalid

2023-10-07 04:42 UTC, SillyBoomer commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
@laihuynhnhatminh CC: @KhaiNd3 
Authentication sử dụng JWT hay cookie đều có ưu và nhược điểm riêng của nó, không có cái nào là hoàn hảo.

Với trình độ hiện giờ của Nhọ, trước tiên là làm quen với quá trình xác thực, jwt hay cookie đều được.

JWT đang sử dụng nhiều không có nghĩa xác thực bằng cookie không ai đụng tới. Cần phải nắm bắt cả 2.

Cứ cho nhọ làm quen với cookie trước, sau này có thể đẻ thêm task xác thực bằng jwt sau.

2023-10-07 04:52 UTC, SillyBoomer commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
@KhaiNd3 
Dùng phương thức xác thực hiện tại, cookie có lưu được credential của user sau khi login/register không?

2023-10-07 04:59 UTC, KhaiNd3 commented on src/utils/validation/validation.js
> +      .regex(/^[a-zA-Z0-9_-]+$/, { message: 'Username is Valid' }),
đã fix

2023-10-07 04:59 UTC, KhaiNd3 commented on src/utils/passportconfig.js
> +  );
đã xóa

2023-10-07 04:59 UTC, KhaiNd3 commented on src/controllers/authController.js
> +    return res.status(201).json(getUser);
đã fix

2023-10-07 04:59 UTC, KhaiNd3 commented on src/controllers/authController.js
> +    const getUser = await User.findOne({ where: { username } });
đã fix

2023-10-07 04:59 UTC, KhaiNd3 commented on index.js
> +    secret: 'mysupersecrect',
đã fix

2023-10-07 05:08 UTC, KhaiNd3 commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
@SillyBoomer @laihuynhnhatminh 
dùng phương thức xác thực hiện tại cookie có lưu credential ( chứng chỉ ) sau khi login và register, khi người dùng đăng nhập thì sever sẽ gửi tập file về có chứa thông tin session id xác thực, trình duyệt sẽ lưu trữ file này và gửi nó cùng với mọi yêu cầu HTTP đến server, phía server sẽ kiểm tra tập file xem thử người dùng đã đăng nhập hay chưa.

2023-10-07 05:12 UTC, KhaiNd3 commented on src/controllers/authController.js
> +    return res.status(400).json('Username Not enough 6 letters');
đã fix

2023-10-07 05:12 UTC, KhaiNd3 commented on src/controllers/authController.js
> +  const CheckPassword = isEnoughLength(password);
đã fix

2023-10-07 05:20 UTC, SillyBoomer commented on src/controllers/authController.js
> +  const getUserData = { ...user.get() };
@KhaiNd3 
Cách thức dặtd tên động từ + danh từ chỉ dùng cho hàm.
Tên biến là danh từ, ví dụ có thể đặt là userData.

2023-10-07 05:23 UTC, SillyBoomer commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
@KhaiNd3 
Nếu quả thực cookie có lưu credential ssau khi login/register, hãy chụp vài tấm hình làm bằng chứng.

2023-10-07 05:28 UTC, KhaiNd3 commented on src/controllers/authController.js
> +    return res.status(400).json('Username Not enough 6 letters');
```
    username: z
      .string({ required_error: 'Username required' })
      .min(6, { message: 'Username not enough 6 letters' })
      .regex(/^[a-zA-Z0-9_-]+$/, { message: 'Username is Valid' }),
```
anh đã define lại username dựa trên thư viện zod, ở đây username sẽ yêu cầu đủ 6 kí tự và không được chứa whitespace hay kí tự đặc biệt và không có kí tự tối đa

2023-10-07 05:33 UTC, KhaiNd3 commented on src/utils/validation/validation.js
> +const isEnoughLength = (val) => {
anh chuyển validator thông thường sang dùng thư viện và tạo schema cho từng chức năng
```
const userRegistrationSchema = z
  .object({
    username: z
      .string({ required_error: 'Username required' })
      .min(6, { message: 'Username not enough 6 letters' })
      .regex(/^[a-zA-Z0-9_-]+$/, { message: 'Username is Valid' }),
    password: z
      .string({ required_error: 'Password required' })
      .min(6, { message: 'Password not enough 6 letters' })
      .regex(/^[a-zA-Z0-9_-]+$/, { message: 'password is Valid' })
      .regex(new RegExp('.*[A-Z].*'), {
        message: 'Password require 1 upscale letter',
      }),
    passwordCfm: z
      .string({ required_error: 'Password confirm required' })
      .min(6, { message: 'Password confirm not enough 6 letters' })
      .regex(/^[a-zA-Z0-9_-]+$/, { message: 'password confirm is Valid' })
      .regex(new RegExp('.*[A-Z].*'), {
        message: 'Password confirm require 1 upscale letter',
      }),
  })
  .refine((data) => data.password === data.passwordCfm, {
    message: 'Password and Password Confirm do not match',
  });
```

2023-10-07 05:34 UTC, KhaiNd3 commented on src/controllers/authController.js
> +  const checkUps = isOneUpscalePass(password);
tương tự như đã cmt các cmt ở trên

2023-10-07 05:35 UTC, KhaiNd3 commented on src/controllers/authController.js
> +  const getUserData = { ...user.get() };
đã sửa tên lại thành userData

2023-10-07 05:39 UTC, KhaiNd3 commented on src/controllers/authController.js
> +      return res.status(201).json(req.isAuthenticated());
@SillyBoomer 
![image](https://github.com/AlterTrap/book-management-be/assets/51858845/2d101c37-f40d-46d3-9441-c46526d1a079)
 cookie mà ứng dụng sử dụng để lưu credential (thường là một token hoặc session cookie) trong ảnh ta có thể thấy dòng connect.sid thì đây là session id dùng để xác thực người dùng đã đăng nhập hay chưa.

2023-10-09 13:11 UTC, merged